const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        theme: "#ff9966",
        status: {
          vouching: "#BE75FF",
          registered: "#00D9A1",
          removed: "#F60C36",
          revocation: "#FF7A00",
          claim: "#00D1FF",
          challenged: "#FFBE66",
          withdrawn: "#999999",
          expired: "#000000",
          transferred: "#3F6212",
          transferring: "#ba7264",
        },
        shade: {
          50: "#fffcfa",
          100: "#fffaf5",
          200: "#fff7f0",
          300: "#fff5eb",
          400: "#fff0e0",
          500: "#ffe0c2",
          600: "#ffD6ad",
        },
      },
      animation: {
        flip: "flip 5s linear infinite",
      },
      keyframes: {
        flip: {
          "0%, 100%": { transform: "rotateY(0deg)" },
          "50%": { transform: "rotateY(360deg)" },
        },
        // progress: {
        //   "0%": { transform: "scaleX(1)" },
        //   "100%": { transform: "scaleX(0)" },
        // },
      },
      fontFamily: {
        sans: ["Open Sans", ...defaultTheme.fontFamily.sans],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
  safelist: [
    "bg-status-vouching",
    "bg-status-registered",
    "bg-status-removed",
    "bg-status-revocation",
    "bg-status-claim",
    "bg-status-challenged",
    "bg-status-withdrawn",
    "bg-status-expired",
    "bg-status-transferred",
    "bg-status-transferring",
    "text-status-vouching",
    "text-status-registered",
    "text-status-removed",
    "text-status-revocation",
    "text-status-claim",
    "text-status-challenged",
    "text-status-withdrawn",
    "text-status-expired",
    "text-status-transferred",
    "text-status-transferring",
    "border-status-vouching",
    "border-status-registered",
    "border-status-removed",
    "border-status-revocation",
    "border-status-claim",
    "border-status-challenged",
    "border-status-withdrawn",
    "border-status-expired",
    "border-status-transferred",
    "border-status-transferring",
  ],
};
