const defaultTheme = require("tailwindcss/defaultTheme");

module.exports = {
  darkMode: ["class", '[data-theme="dark"]'],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        light: {
          whiteBackground: "#FFFFFF",
          stroke: "#E5E5E5",
          theme: "#ff9966",
          primaryText: "#333333",
          secondaryText: "#999999",
          orange: "#FF9966",
          status: {
            vouching: "#BE75FF",
            registered: "#00D9A1",
            removed: "#F60C36",
            revocation: "#FF7A00",
            claim: "#00D1FF",
            challenged: "#FFBE66",
            withdrawn: "#999999",
            expired: "#000000",
            transferred: "#3F6212",
            transferring: "#ba7264",
          },
          shade: {
            50: "#fffcfa",
            100: "#fffaf5",
            200: "#fff7f0",
            300: "#fff5eb",
            400: "#fff0e0",
            500: "#ffe0c2",
            600: "#ffd6ad",
          },
        },
        dark: {
          whiteBackground: "#2D0050",
          stroke: "#42498F",
          theme: "#1b003f",
          primaryText: "#DAF0FF",
          secondaryText: "#BECCE5",
          orange: "#FFBE66",
          status: {
            vouching: "#7C3AED",
            registered: "#0ACF83",
            removed: "#F44336",
            revocation: "#FF5722",
            claim: "#03A9F4",
            challenged: "#FFC107",
            withdrawn: "#BDBDBD",
            expired: "#9E9E9E",
            transferred: "#8BC34A",
            transferring: "#795548",
          },
          shade: {
            50: "#1b003f",
            100: "#4d4d4d",
            200: "#666666",
            300: "#808080",
            400: "#999999",
            500: "#b3b3b3",
            600: "#cccccc",
          },
        },
      },
      animation: {
        flip: "flip 5s linear infinite",
      },
      keyframes: {
        flip: {
          "0%, 100%": { transform: "rotateY(0deg)" },
          "50%": { transform: "rotateY(360deg)" },
        },
        // progress: {
        //   "0%": { transform: "scaleX(1)" },
        //   "100%": { transform: "scaleX(0)" },
        // },
      },
      fontFamily: {
        sans: ["Open Sans", ...defaultTheme.fontFamily.sans],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
  safelist: [
    "bg-status-vouching",
    "bg-status-registered",
    "bg-status-removed",
    "bg-status-revocation",
    "bg-status-claim",
    "bg-status-challenged",
    "bg-status-withdrawn",
    "bg-status-expired",
    "bg-status-transferred",
    "bg-status-transferring",
    "text-status-vouching",
    "text-status-registered",
    "text-status-removed",
    "text-status-revocation",
    "text-status-claim",
    "text-status-challenged",
    "text-status-withdrawn",
    "text-status-expired",
    "text-status-transferred",
    "text-status-transferring",
    "border-status-vouching",
    "border-status-registered",
    "border-status-removed",
    "border-status-revocation",
    "border-status-claim",
    "border-status-challenged",
    "border-status-withdrawn",
    "border-status-expired",
    "border-status-transferred",
    "border-status-transferring",
  ],
};
