export enum PoHContract {
  PROOF_OF_HUMANITY = "PROOF_OF_HUMANITY",
  CROSS_CHAIN_POH = "CROSS_CHAIN_POH",
  ARBITRATOR = "ARBITRATOR",
  TOKEN = "TOKEN",
  POH_TOKEN_MANAGER = "POH_TOKEN_MANAGER",
  GROUP_CURRENCY_TOKEN = "GROUP_CURRENCY_TOKEN",
  HUB = "HUB",
}
