query Contract {
  contract(id: "0x00") {
    baseDeposit
    humanityLifespan
    renewalPeriodDuration
    challengePeriodDuration
    requiredNumberOfVouches
    latestArbitratorHistory {
      arbitrator
      extraData
      updateTime
      registrationMeta
      clearingMeta
    }
  }
  crossChainGateways {
    id
    foreignProxy
  }
}
