query Request($id: ID!) {
  request(id: $id) {
    status {
      id
    }
    index
    revocation
    requester
    creationTime
    lastStatusChange
    vouches {
      voucher {
        id
      }
    }
    humanity {
      id
      nbRequests
      nbLegacyRequests
      registration {
        claimer {
          id
        }
      }
      ...winnerClaim
    }
    claimer {
      id
      name
      vouchesReceived {
        from {
          id
          registration {
            expirationTime
            humanity {
              vouching
            }
          }
        }
        humanity {
          id
        }
      }
      vouches {
        for {
          id
          name
        }
      }
    }
    evidenceGroup {
      evidence(orderBy: creationTime, orderDirection: desc) {
        id
        uri
        creationTime
        submitter
      }
    }
    challenges(orderBy: creationTime) {
      id
      reason {
        id
      }
      disputeId
      challenger {
        id
      }
      nbRounds
      rounds(orderBy: creationTime) {
        requesterFund {
          amount
        }
        challengerFund {
          amount
        }
      }
    }
    arbitratorHistory {
      updateTime
      registrationMeta
    }
  }
}
