fragment winnerClaim on Humanity {
  winnerClaim: requests(
    where: { 
      or: [
        {
          revocation: false, 
          status: "resolved", 
          winnerParty: "requester" 
        },
        {
          revocation: false, 
          status: "transferring", 
          winnerParty: "requester" 
        }
      ]
    }
    orderBy: resolutionTime
    orderDirection: desc
    first: 1
  ) {
    index
    resolutionTime
    evidenceGroup {
      evidence(orderBy: creationTime, first: 1) {
        uri
      }
    }
  }
}